export default {
    SET_SPEECH_OPTION: 'SET_SPEECH_OPTION',
    SET_NOTE: 'SET_NOTE',
    SET_NOTE_SETTING: 'SET_NOTE_SETTING',
    SET_NOTE_COMMENTS: 'SET_NOTE_COMMENTS',
    SET_NOTE_IMAGE_URLS: 'SET_NOTE_IMAGE_URLS',
    SET_NOTE_TRANSLATE: 'SET_NOTE_TRANSLATE',
    CLR_NOTE_COMMENT: 'CLR_NOTE_COMMENT',
};
